//    top.sv - Minimig on tang nano 20k toplevel

// =========================================================================
// To use Kick Switch Lite, the ROMs must be flashed like this:
//
// 0x400000 Kickstart 3.1 / 512k (default)
// 0x700000 Kickstart 1.3 / 256k 
// 0x740000 Kickstart 1.3 / 256k 
// 0x780000 Kickstart 3.2 / 512k 
//
// for example:
// openFPGALoader --external-flash -o 0x400000 kick31.rom
// =========================================================================

`define ENABLE_TG68K
`define ENABLE_AGA   // offer the AGA chipset in the menu
`define CPU_SLOW14   // run TG68K at 14MHz effective (A1200 speed) for timing closure
`define ENABLE_CACHE // MiSTer cpu cache between the cpu and the sdram (cached kickstart + fast ram)
`define CHIPRAM_CACHE
// `define DISABLE_IDE  // v32 experiment: cache + ide together
// `define NO_WS2812   // drop the rgb status led to make room for cache + ide
`define DENISE_EBR   // block ram based bitplane and sprite buffers, saves logic
`define DISABLE_ROM_LOADER // drop the rom loader to make room 
// `define ENABLE_DRIVE_SOUNDS

module top(
  input			clk,

  input			reset, // button S2
  input			user,  // button S1

  output [5:0]	leds_n,
  output		ws2812,

  // spi flash interface
  output		mspi_cs,
  output		mspi_clk,
  inout			mspi_di,
  inout			mspi_hold,
  inout			mspi_wp,
  inout			mspi_do,

  // "Magic" port names that the gowin compiler connects to the on-chip SDRAM
  output		O_sdram_clk,
  output		O_sdram_cke,
  output		O_sdram_cs_n,  // chip select
  output		O_sdram_cas_n, // columns address select
  output		O_sdram_ras_n, // row address select
  output		O_sdram_wen_n, // write enable
  inout [31:0]	IO_sdram_dq, // 32 bit bidirectional data bus
  output [10:0]	O_sdram_addr, // 11 bit multiplexed address bus
  output [1:0]	O_sdram_ba, // two banks
  output [3:0]	O_sdram_dqm, // 32/4

  // internal lcd
  output                lcd_dclk,
  output                lcd_hs, // lcd horizontal synchronization
  output                lcd_vs, // lcd vertical synchronization        
  output                lcd_bl, // lcd backlight enable
  output                lcd_de, // lcd data enable     
  output [4:0]  lcd_r,  // lcd red
  output [5:0]  lcd_g,  // lcd green
  output [4:0]  lcd_b,  // lcd blue

  // SD card slot
  output		sd_clk,
  inout			sd_cmd, // MOSI
  inout [3:0]	sd_dat, // 0: MISO
	   
  // SPI connection to ob-board BL616. By default an external
  // connection is used with a M0S Dock
  input			spi_sclk,
  input			spi_csn,
  output		spi_dir,
  input			spi_dat,
  output		spi_irqn,

  // audio
  output                hp_bck,
  output                hp_ws,
  output                hp_din,
  output                pa_en		   
);
`default_nettype none
  
wire [5:0]	leds;
assign leds[5] = |sd_wr;
assign leds[4] = |sd_rd;
assign leds_n = ~leds;


// ============================== clock generation ===========================
   
// HDMI clock:  141.8758 MHz
// Pixel clock: 28.37516 MHz (HDMI/5)
// SDRAM and flash clock: 85 MHz
// Amiga clock: 7.09379 (Pixel/4)
   
// 27MHz crystal * 19/6 = 85.5MHz, divided by 3. The nominal PAL clock would
// be 28.37516MHz, but this is the one the hardware actually runs at, and the
// audio rate below is derived from it.
`define PIXEL_CLOCK 28500000

wire clk_pixel_x5;   
wire pll_lock;   
wire clk_7;
wire clk_28m;
wire clk_85m;
wire clk_85m_shifted;
wire clk_pixel;

amigaclks amigaclks (
	.clk_in(clk),
	.clk_7m(clk_7), // Unused
	.clk_28m(clk_28m),
	.clk_85m(clk_85m),
	.clk_sdram(clk_85m_shifted),
	.locked(pll_lock),
	.vidmode(1'b1),
	.clk_tmds(clk_pixel_x5),
	.clk_pixel(clk_pixel),
	.video_locked()
);

wire rst_28m, rst_28m_n;
wire rst_85m, rst_85m_n;
wire rst_sdram, rst_sdram_n;

wire sdram_ready;

rst_sync rst_sync (
  .clk_28m(clk_28m),
  .clk_85m(clk_85m),
  .pll_lock(pll_lock),
  .sdram_ready(sdram_ready),
  .rst_28m(rst_28m),
  .rst_28m_n(rst_28m_n),
  .rst_85m(rst_85m),
  .rst_85m_n(rst_85m_n),
  .rst_sdram(rst_sdram),
  .rst_sdram_n(rst_sdram_n)
);

wire	clk7_en;
wire	clk7n_en;

// control signals generated by the user via the OSD
wire 	   osd_reset;   
wire [1:0] osd_chipmem;         // 0=512k, 1=1M, 2=1.5M, 3=2M
wire [1:0] osd_slowmem;         // 0=None, 1=512k, 2=1M, 3=1.5M
wire [1:0] osd_fastmem;         // 0=None, 1=2M, 2=4M, 3=5.5M (stolen from SlowRAM)
wire [1:0] osd_floppy_drives;
wire       osd_floppy_turbo;
wire       osd_floppy_wrprot;
wire       osd_ide_enable;
wire [2:0] osd_chipset;         // 0=OCS-A500, 1=OCS-A1000, 2=ECS, 6=AGA
wire [1:0] osd_cpu;             // 00=68000, 01=68010, 11=68020
wire       osd_video_mode;      // PAL (0=PAL, 1=NTSC)
wire [1:0] osd_video_filter;
wire [1:0] osd_video_scanlines;
wire [2:0] osd_turbo;           // 001=turbochip, 010=turbokick, 100=chipcache
wire       osd_joy_swap;        // 0=off, 1=on
wire [2:0] osd_volume;          // Mute=0, 1=25%, 2=50%, 3=75%, 4=100%
wire [7:0] osd_lcd_v_pos;       // -20 .. 20 vertical offset for lcd adjustment
wire [1:0] osd_kickstart;       // 1=1.3, 2=3.1, 3=3.2
wire 	   osd_drive_sounds;   	// 0 = disabled, 1 = enabled

wire	   rom_download_in_progress;

// this is the reset that goes into the nanomig itself
reg nanomig_reset = 1;

always @(posedge clk_28m, posedge rst_28m) begin
    if (rst_28m)
        nanomig_reset <= 1'b1;
    else
        nanomig_reset <= !rom_done || reset || osd_reset || kbd_reset || rom_download_in_progress;
end

// connect to ws2812 led. The rgb status led costs ~150 luts which the cache
// plus ide combination needs, so it is dropped when space is tight.
wire [23:0] ws2812_color;
`ifdef NO_WS2812
assign ws2812 = 1'b0;
`else
ws2812 ws2812_inst (
    .clk(clk_28m),
	.reset(rst_28m),
    .color(ws2812_color),
    .data(ws2812)
);
`endif

// interface to M0S MCU
wire       mcu_sys_strobe;        // mcu message byte valid for sysctrl
wire       mcu_hid_strobe;        // -"- hid
wire       mcu_osd_strobe;        // -"- osd
wire       mcu_sdc_strobe;        // -"- sdc
wire       mcu_start;             // first byte of MCU message

wire [7:0] mcu_data_out;  

wire [7:0] sys_data_out;  
wire [7:0] hid_data_out;  
wire [7:0] osd_data_out = 8'h55;  // OSD actually has no data output
wire [7:0] sdc_data_out;

mcu_spi mcu (
	 .clk(clk_28m),
	 .reset(rst_28m),

	 // SPI interface to FPGA Companion
     .spi_io_ss ( spi_csn ),
     .spi_io_clk( spi_sclk  ),
     .spi_io_din( spi_dat ),
     .spi_io_dout( spi_dir ),

	 // byte wide data in/out to the submodules
     .mcu_sys_strobe(mcu_sys_strobe),
     .mcu_hid_strobe(mcu_hid_strobe),
     .mcu_osd_strobe(mcu_osd_strobe),
     .mcu_sdc_strobe(mcu_sdc_strobe),
     .mcu_start(mcu_start),
     .mcu_dout(mcu_data_out),
     .mcu_sys_din(sys_data_out),
     .mcu_hid_din(hid_data_out),
     .mcu_osd_din(osd_data_out),
     .mcu_sdc_din(sdc_data_out)
);

// decode SPI/MCU data received for human input devices (HID) and
// convert into Amiga compatible mouse and keyboard signals
wire [7:0] int_ack;
wire hid_int;
wire hid_iack = int_ack[1];
wire sdc_iack = int_ack[3];
wire sdc_int;
wire [7:0] hid_joy0;
wire [7:0] hid_joy1;
   
// signals to wire the floppy controller to the sd card
wire [7:0]  sd_rd;
wire [7:0]  sd_wr;
wire [7:0]  sd_rd_data;
wire [7:0]  sd_wr_data;
wire [31:0] sd_sector;  
wire [8:0]  sd_byte_index;
wire        sd_rd_byte_strobe;
wire        sd_busy, sd_done;
wire [63:0] sd_img_size;
wire [7:0]  sd_img_mounted;
reg         sd_ready;

// state machine handling kickstart upload from Companion
reg [2:0]	 kick_upload_state = 3'd0;
reg		     kick_is_256k; 
assign	     rom_download_in_progress = kick_upload_state >= 3'd1 && kick_upload_state <= 3'd3;
   
wire		 rom_data_available;   
wire [7:0]	 rom_data;
reg		     rom_data_strobe;
reg		     rom_data_byte_toggle;
   
reg [7:0]	 rom_data_lowbyte;   
reg [15:0]	 rom_data_word;   
reg [18:1]	 rom_data_addr;   
reg		     rom_data_word_we;

wire [2:0]   rom_selected;           // Index 0-7 of image selected by companion
wire		 rom_selection_strobe;   // image is being selected
wire		 kickrom_size_valid = (sd_img_size == 64'd524288 || sd_img_size == 64'd262144);
wire		 rom_accepted = (rom_selection_strobe && rom_selected == 3'd0) && kickrom_size_valid;

wire [18:1]	 rom_data_addr_max = ((kick_is_256k?'d262144:'d524288)/2)-1;

`ifndef DISABLE_ROM_LOADER 
// The ROM uploader receives ROM data from the Companion and writes it into
// the area of sdram that is reserved for kickstart rom  
always @(posedge clk_28m, posedge rst_28m) begin
   if(rst_28m) begin
      kick_upload_state <= 3'd0;
      rom_data_word_we <= 1'b0;
	  kick_is_256k <= 1'b0;	  
   end else begin
      rom_data_strobe <= 1'b0;		 
      if(clk7_en && rom_data_word_we) begin
		 rom_data_word_we <= 1'b0;
		 if(rom_data_addr != rom_data_addr_max)
      	   rom_data_addr <= rom_data_addr + 18'd1;   
      end

      case(kick_upload_state)
		3'd0: begin
		   // FPGA Companion wants to upload a rom to slot 0 with 256k or 512k size
		   if(rom_selection_strobe) begin
			  // At this point rom_selected could be used to handle the different
			  // rom images appropriately. The Amiga/NanoMig only supports one rom image			  
			  if(rom_accepted) begin
				 $display("nanomig_rb.v: Request kickstart upload, size = %0d", sd_img_size);
				 kick_upload_state <= 3'd1;
				 kick_is_256k <= (sd_img_size == 64'd262144);
				 rom_data_byte_toggle <= 1'b0;
				 rom_data_addr <= 18'd0;
			  end else
				$display("nanomig_tb.v: Kickstart upload rejected, size = %0d", sd_img_size);
		   end
		end
		
		3'd1: begin
		   // sync to amiga 7 Mhz clock
		   if(clk7n_en)
			 kick_upload_state <= 3'd2;
		end
		
		3'd2: begin
		   // transfer kickstart from sd card fifo
		   // (byte) data is being read on both 7Mhz edges, so 16 bit data is ready
		   // every positive 7 Mhz edge
		   if(rom_data_available) begin
			  // odd byte on falling edge
			  if(clk7n_en && !rom_data_byte_toggle) begin		 
				 rom_data_lowbyte <= rom_data;
				 rom_data_strobe <= 1'b1;  // notify SD card driver that byte has been read
				 rom_data_byte_toggle <= 1'b1;				 
			  end
			  // even byte on rising edge
			  if(clk7_en && rom_data_byte_toggle) begin
				 rom_data_word <= { rom_data_lowbyte, rom_data };				 
				 rom_data_strobe <= 1'b1;  // notify SD card driver that byte has been read
				 rom_data_word_we <= 1'b1; // 16 bit data is ready
				 rom_data_byte_toggle <= 1'b0;				 
				 
				 // check if kickstart is complete
				 if(rom_data_addr == rom_data_addr_max)
				   kick_upload_state <= 3'd3;
			  end
		   end	   
		end // case: 3'd2
		
		3'd3:
		  if(clk7_en) begin
			 $display("nanomig_tb.v: ROM upload complete");		    
			 kick_upload_state <= 3'd4;
		  end
		
		3'd4:
		  kick_upload_state <= 3'd0;
		
      endcase	 
   end   
end
`endif // DISABLE_ROM_LOADER

sd_card #(
    .CLK_DIV(3'd0),                  // for 28 Mhz clock
    .IMAGE_FIFO_BITS(9)              // ROM transfer fifo size = 512
) sd_card (
    .rstn(rst_28m_n),               // rstn active-low, 1:working, 0:reset
    .clk(clk_28m),                   // clock
  
    // SD card signals
    .sdclk(sd_clk),
    .sdcmd(sd_cmd),
    .sddat(sd_dat),

    // mcu interface
    .data_strobe(mcu_sdc_strobe),
    .data_start(mcu_start),
    .data_in(mcu_data_out),
    .data_out(sdc_data_out),

    // output file/image information. Image size is e.g. used by fdc to 
    // translate between sector/track/side and lba sector
    .image_mounted(sd_img_mounted),
    .image_size(sd_img_size),           // length of image file

    `ifndef DISABLE_ROM_LOADER 
    // rom download interface
    .rom_image_selected(rom_selected),  // image_size is valid for this
    .rom_image_selection_strobe(rom_selection_strobe),
    .rom_image_accepted(rom_accepted),
    .rom_image_data_available(rom_data_available),
    .rom_image_data(rom_data),
    .rom_image_data_strobe(rom_data_strobe),
		`endif // DISABLE_ROM_LOADER

    // interrupt to signal communication request
    .irq(sdc_int),
    .iack(sdc_iack),

    // user read sector command interface (sync with clk32)
    .rstart(sd_rd), 
    .wstart(sd_wr), 
    .rsector(sd_sector),
    .rbusy(sd_busy),
    .rdone(sd_done),

    // sector data output interface (sync with clk32)
    .inbyte(sd_wr_data),
    .outen(sd_rd_byte_strobe), // when outen=1, a byte of sector content is read out from outbyte
    .outaddr(sd_byte_index),   // outaddr from 0 to 511, because the sector size is 512
    .outbyte(sd_rd_data)       // a byte of sector content
);

// keyboard and mouse interface to Minimig
wire [2:0] mouse_buttons; // mouse buttons
wire	   kbd_mouse_level;  
wire [1:0] kbd_mouse_type;  
wire [7:0] kbd_mouse_data;  
wire       kbd_reset;      // keyboard reset (Ctrl+LAmiga+RAmiga)

hid hid (
        .clk(clk_28m),
        .reset(rst_28m),

         // interface to receive user data from MCU (mouse, kbd, ...)
        .data_in_strobe(mcu_hid_strobe),
        .data_in_start(mcu_start),
        .data_in(mcu_data_out),
        .data_out(hid_data_out),

        // input local db9 port events to be sent to MCU. Changes also trigger
        // an interrupt, so the MCU doesn't have to poll for joystick events
        .db9_port( 6'b000000 ),
        .irq( hid_int ),
        .iack( hid_iack ),

		 // keyboard & mouse				 
		 .mouse_buttons(mouse_buttons), // mouse buttons
		 .kbd_mouse_level(kbd_mouse_level),  
		 .kbd_mouse_type(kbd_mouse_type),  
		 .kbd_mouse_data(kbd_mouse_data),
		 
        .kbd_reset(kbd_reset),
        .joystick0(hid_joy0),
        .joystick1(hid_joy1)
         );   

sysctrl #(
`ifdef ENABLE_AGA
        .AGA(1)
`endif
        ) sysctrl (
        .clk(clk_28m),
        .reset(rst_28m),

         // interface to send and receive generic system control
        .data_in_strobe(mcu_sys_strobe),
        .data_in_start(mcu_start),
        .data_in(mcu_data_out),
        .data_out(sys_data_out),

        // values controlled by the OSD
	.system_reset(osd_reset),
	.system_floppy_drives(osd_floppy_drives),
	.system_floppy_turbo(osd_floppy_turbo),
	.system_floppy_wrprot(osd_floppy_wrprot),
	.system_ide_enable(osd_ide_enable),
	.system_chipset(osd_chipset),
	.system_cpu(osd_cpu),
	.system_video_mode(osd_video_mode),
	.system_video_filter(osd_video_filter),
	.system_video_scanlines(osd_video_scanlines),
	.system_chipmem(osd_chipmem),
	.system_slowmem(osd_slowmem),
	.system_fastmem(osd_fastmem),
	.system_turbo(osd_turbo),
	.system_joy_swap(osd_joy_swap),
	.system_volume(osd_volume),
  	.system_kickstart(osd_kickstart),
    .system_lcd_v_pos(osd_lcd_v_pos),

        .int_out_n(spi_irqn),
        .int_in( { 4'b0000, sdc_int, 1'b0, hid_int, 1'b0 }),
        .int_ack( int_ack ),

        .buttons( {user, reset} ),
        .leds(),
        .color(ws2812_color)
);
   
// digital 12 bit video
wire hs_n, vs_n;
wire [3:0] red;
wire [3:0] green;
wire [3:0] blue;
   
wire [5:0] video_red;
wire [5:0] video_green;
wire [5:0] video_blue;   

// map to rgb565
assign lcd_r = video_red[5:1];
assign lcd_g = video_green;
assign lcd_b = video_blue[5:1];  

osd_u8g2 osd_u8g2 (
        .clk(clk_28m),
        .reset(rst_28m),

        .data_in_strobe(mcu_osd_strobe),
        .data_in_start(mcu_start),
        .data_in(mcu_data_out),

        .hs(hs_n),
        .vs(vs_n),

        .r_in({red,   2'b00}),
        .g_in({green, 2'b00}),
        .b_in({blue,  2'b00}),

        .r_out(video_red),
        .g_out(video_green),
        .b_out(video_blue)
);   

/* ---------------------- Minimig chipset ----------------------- */

// two 15 bit audio channels
wire [14:0] audio_left;
wire [14:0] audio_right;   

// Map Joysticks 

            // map first HID/USB joystick into first amiga joystick port
            // wire in db9 joystick & mouse
wire [7:0] physical_port_1 = hid_joy0;

            // map second HID/USB joystick into second amiga joystick port
            // wire in db9 joystick
wire [7:0] physical_port_2 = hid_joy1;
              
wire [7:0] joystick0;
wire [7:0] joystick1;

// Swap Joysticks 

assign joystick0 = osd_joy_swap ? physical_port_1 : physical_port_2;
assign joystick1 = osd_joy_swap ? physical_port_2 : physical_port_1;

wire [23:1] cpu_a;
wire cpu_as_n, cpu_lds_n, cpu_uds_n;
wire cpu_rw, cpu_dtack_n;
wire [2:0] ipl_n;
wire [15:0] cpu_din, cpu_dout;       

// Minimig ram/rom interface
wire [23:1] ram_a;
wire [15:0] ram_din;
wire [15:0] ram_dout;
wire 	    ram_we_n;
wire [1:0]  ram_be;
wire 	    ram_oe_n;
wire		ram_refresh;   

wire fastram_sel;
wire [22:1] fastram_addr;
wire fastram_lds;
wire fastram_uds;
wire [15:0] fastram_dout;
wire [15:0] fastram_din;
wire [1:0] fastram_be = {fastram_uds,fastram_lds};  
wire fastram_wr;
wire fastram_ready;
   
wire [15:0] sdram_dout;
wire [47:0] chip48;         // upper 48 bits of 64 bit aligned chipram reads (AGA fmode>0)
wire [47:0] fastram_dout48; // wide read data of the cpu cache port

assign ram_din = sdram_dout;

// pack config values into minimig config
wire [5:0] chipset_config = { 1'b0,osd_chipset,osd_video_mode,1'b0 };
wire [1:0] cpu_config = { |osd_cpu ? 2'b11 : 2'b00 };
wire [7:0] memory_config = { 4'b0_000, osd_slowmem, osd_chipmem };   
wire [2:0] fastram_config = { 1'b0, osd_fastmem };   
wire [2:0] turbo_config = { osd_turbo };
wire [3:0] floppy_config = { osd_floppy_drives, osd_floppy_wrprot, osd_floppy_turbo };
wire [3:0] video_config = { osd_video_filter, osd_video_scanlines };   
// FIXME - setting ide_config[5] prevents minimig from using
// fast chipset bus for GAYLE, which is by default in use
// when 68020 CPU is selected; we may connect fast chip bus
// to GAYLE and set ide_config[5] to 0 to improve performance
wire [5:0] ide_config = { 5'b10000, osd_ide_enable };   
   
nanomig nanomig
(
 .clk_sys(clk_28m),
 .reset(nanomig_reset),
 .por(rst_28m),

 .clk7_en(clk7_en),
 .clk7n_en(clk7n_en),

 .pwr_led(leds[0]),
 .fdd_led(leds[1]),
`ifndef DISABLE_IDE
 .hdd_led(leds[2]),
`endif
 
 .memory_config(memory_config),
 .fastram_config(fastram_config),
 .cpu_config(cpu_config),
 .chipset_config(chipset_config),
 .floppy_config(floppy_config),
 .video_config(video_config),
 .turbo_config(turbo_config),
`ifndef DISABLE_IDE
 .ide_config(ide_config),
`endif

 // video
 .hs(hs_n), // horizontal sync
 .vs(vs_n), // vertical sync
 .r(red),
 .g(green),
 .b(blue),

 .audio_left(audio_left),
 .audio_right(audio_right),

 // uart interface 
 .uart_rx(1'b1),
 .uart_tx(),
 
 // keyboard & mouse				 
 .mouse_buttons(mouse_buttons), // mouse buttons
 .kbd_mouse_level(kbd_mouse_level),  
 .kbd_mouse_type(kbd_mouse_type),  
 .kbd_mouse_data(kbd_mouse_data),
 .joystick0(joystick0),
 .joystick1(joystick1),
				 
 // sd card interface for floppy disk and hdd emulation
 .sdc_img_size(sd_img_size),
 .sdc_img_mounted(sd_img_mounted), 
 .sdc_rd(sd_rd),
 .sdc_wr(sd_wr),
 .sdc_sector(sd_sector),
 .sdc_busy(sd_busy),
 .sdc_done(sd_done), 
 .sdc_byte_in_strobe(sd_rd_byte_strobe),
 .sdc_byte_addr(sd_byte_index),
 .sdc_byte_in_data(sd_rd_data),
 .sdc_byte_out_data(sd_wr_data),
 
 // (s)ram interface
 .ram_data(ram_dout),       // sram data bus
 .ram_address(ram_a),       // sram address bus
 .ramdata_in(ram_din),      // sram data bus in
 ._ram_bhe(ram_be[1]),      // sram upper byte select
 ._ram_ble(ram_be[0]),      // sram lower byte select
 ._ram_we(ram_we_n),        // sram write enable
 ._ram_oe(ram_oe_n),        // sram output enable
`ifdef ENABLE_AGA
 .chip48(chip48),
`else
 .chip48(48'b0),
`endif
 .refresh(ram_refresh),
 
 .fastram_sel(fastram_sel),
 .fastram_addr(fastram_addr),
 .fastram_lds(fastram_lds),
 .fastram_uds(fastram_uds),
 .fastram_dout(fastram_dout),
`ifdef ENABLE_CACHE
 .fastram_dout48(fastram_dout48),
`else
 .fastram_dout48(48'b0),
`endif
 .fastram_din(fastram_din),
 .fastram_wr(fastram_wr),
 .fastram_ready(fastram_ready)
);

wire flash_ready;

reg flash_ready_d1;
reg flash_ready_d2;

// synchronize flash_ready signal to 28MHz clock domain
always @(posedge clk_28m, posedge rst_28m) begin
   if (rst_28m) begin
      flash_ready_d1 <= 1'b0;
      flash_ready_d2 <= 1'b0;
   end else begin
      flash_ready_d1 <= flash_ready;
      flash_ready_d2 <= flash_ready_d1;
   end
end

/* -------------- state machine copying data from flash to sdram ---------------- */
reg  [21:0] flash_addr = 22'h200000;
reg  [17:0] flash_ram_addr = 18'h0;
reg  [31:0] word_count = 32'h40000;

wire [15:0] flash_dout;
reg         flash_cs;
wire        flash_data_strobe;
wire        flash_busy;
reg         flash_ram_write;

// once the copy counter has run to zero, all rom has been copied
wire        rom_done = (word_count == 0);

assign leds[3] = !rom_done || rom_download_in_progress;

/* -------------- detect osd_kickstart change and trigger reload ---------------- */
reg [1:0] osd_kickstart_last = 2'b00;
reg       kickstart_reload   = 1'b0;

always @(posedge clk_28m) begin
  osd_kickstart_last <= osd_kickstart;
  kickstart_reload   <= (osd_kickstart != osd_kickstart_last);
end

localparam FLASH_STATE_INIT  = 0;
localparam FLASH_STATE_READ  = 1;
localparam FLASH_STATE_WAIT  = 2;
localparam FLASH_STATE_WRITE = 3;
localparam FLASH_STATE_NEXT  = 4;

reg [2:0] flash_state;

always @(posedge clk_28m, posedge rst_28m, posedge reset) begin
  if (rst_28m || reset || kickstart_reload) begin
    flash_state <= FLASH_STATE_INIT;

  end else begin
    case (flash_state)
      FLASH_STATE_INIT: begin
        if (clk7n_en && flash_ready_d2) begin
          case(osd_kickstart)
                  2'b00: flash_addr <= 22'h380000; // Kickstart 1.3 (at 7,0 MB)
                  2'b01: flash_addr <= 22'h200000; // Kickstart 3.1 (at 4,0 MB)
                  2'b10: flash_addr <= 22'h3C0000; // Kickstart 3.2 (at 7,5 MB)
                  default: flash_addr <= 22'h200000;
          endcase
          flash_ram_addr <= 18'h0;
          word_count     <= 32'h40000;

          flash_cs        <= 0;
          flash_ram_write <= 0;
          flash_state     <= FLASH_STATE_READ;
        end
      end
      FLASH_STATE_READ: begin
        if (word_count != 0) begin
          flash_cs    <= 1;
          flash_state <= FLASH_STATE_WAIT;
        end
      end
      FLASH_STATE_WAIT: begin
        if (flash_busy) begin
          flash_cs    <= 0;
          flash_state <= FLASH_STATE_WRITE;
        end
      end
      FLASH_STATE_WRITE: begin
        if (!flash_busy && clk7_en) begin
          flash_ram_write <= 1;
          flash_state     <= FLASH_STATE_NEXT;
        end
      end
      FLASH_STATE_NEXT: begin
        if (clk7n_en) begin
          flash_ram_write <= 0;
          flash_ram_addr  <= flash_ram_addr + 1;
          flash_addr      <= flash_addr + 1;
          flash_state     <= FLASH_STATE_READ;
          word_count      <= word_count - 1;
        end
      end
      default: begin
        flash_state <= FLASH_STATE_INIT;
      end
    endcase
  end
end

// ----------------------------- SDRAM ---------------------------------

// there's a total of 16 sdram segments of 512kBytes. The last
// one is being used to store the kick romm

wire        sdram_access  = (!ram_oe_n || !ram_we_n);
wire	    sdram_rw      = !ram_we_n;


// multiplex ram input to the three sources
//  1. the minimig addressing ram during regular operation
//  2. flash rom being copied to ram after core load
//  3. flash rom download to ram initiated by the companion

wire		sdram_cs      =
			!rom_done?flash_ram_write:
			rom_download_in_progress?rom_data_word_we:
			sdram_access;

wire        sdram_sync    = clk7_en;
   
wire		sdram_refresh = 
			!rom_done?1'b0:
			rom_download_in_progress?1'b0:
			ram_refresh;

wire [15:0] sdram_din     =
			!rom_done?flash_dout:                    // initial rom download from flash
			rom_download_in_progress?rom_data_word:  // rom download from sd card
			ram_dout;                                // regular operation
   
wire [1:0]  sdram_be      =
			!rom_done?2'b00:                         // flash download always does word access
			rom_download_in_progress?2'b00:          //          -"-
			ram_be;                                  // byte enable during regular operation is via ds[1:0]

// check if the sdram access goes into the ram segments used to store kickrom and if
// a 256k kick has been downloaded
wire		 minimig_is_accessing_rom = ram_a[22:19] == 4'b1111;
wire		 minimig_is_accessing_256k_rom = kick_is_256k && minimig_is_accessing_rom;   

wire		sdram_we      = 
			!rom_done?flash_ram_write:               // flash download write enable			
			rom_download_in_progress?rom_data_word_we:
			// the following test is needed as the rom kick area is also accessible to the
			// minimig through the fastram area at $780000
			(sdram_rw && !minimig_is_accessing_rom); // regular ram write as requested by the cpu or chipset

wire [21:0] sdram_addr    = 
			!rom_done?{4'b1111, flash_ram_addr}:                // initial rom download from flash
			rom_download_in_progress?{4'b1111, rom_data_addr}:  // rom download from sd card
			minimig_is_accessing_256k_rom?{ram_a[22:19],1'b0,ram_a[17:1]}:  // regular rom access into 256k kickstart
			ram_a[22:1];                                        // regular operation

assign O_sdram_clk = clk_85m_shifted;

localparam CHIP48_BURST = 0
`ifdef ENABLE_AGA
    | 1
`endif
`ifdef ENABLE_CACHE
    | 1
`endif
;

sdram #(
    .DATA_WIDTH(32),
    .RAS_WIDTH(11),
    .CAS_WIDTH(8),
    .CHIP48_BURST(CHIP48_BURST)   // the wide 64 bit fetch AGA or cache needs
) sdram (
	.sd_data    ( IO_sdram_dq   ), // 32 bit bidirectional data bus
	.sd_addr    ( O_sdram_addr  ), // 11 bit multiplexed address bus
	.sd_dqm     ( O_sdram_dqm   ), // two byte masks
	.sd_ba      ( O_sdram_ba    ), // two banks
	.sd_cs      ( O_sdram_cs_n  ), // a single chip select
	.sd_we      ( O_sdram_wen_n ), // write enable
	.sd_ras     ( O_sdram_ras_n ), // row address select
	.sd_cas     ( O_sdram_cas_n ), // columns address select
	.sd_cke     ( O_sdram_cke   ), // SDRAM clock enable

	// cpu/chipset interface
	.clk        ( clk_85m       ), // sdram is accessed at 85MHz
	.reset_n    ( rst_sdram_n   ), // init signal after FPGA config to initialize RAM

	.ready      ( sdram_ready   ), // ram is ready and has been initialized
	.sync       ( sdram_sync    ), // rising edge of sync is begin of a memory cycle
	.refresh    ( sdram_refresh ), // refresh cycle

	.din        ( sdram_din     ), // data input from chipset/cpu
	.dout       ( sdram_dout    ),
	.dout48     ( chip48        ), // wide fetch data for AGA fmode>0
	.addr       ( sdram_addr    ), // 22 bit word address
	.ds         ( sdram_be      ), // upper/lower data strobe
	.cs         ( sdram_cs      ), // cpu/chipset requests read/wrie
	.we         ( sdram_we      ),  // cpu/chipset requests write

	.p2_din        ( fastram_din     ), // data input from chipset/cpu
	.p2_dout       ( fastram_dout    ),
	.p2_dout48     ( fastram_dout48  ), // wide read data for the cache line fills
	.p2_addr       ( fastram_addr    ), // 22 bit word address
	.p2_ds         ( fastram_be      ), // upper/lower data strobe
	.p2_cs         ( fastram_sel     ), // cpu/chipset requests read/wrie
	.p2_we         ( fastram_wr      ),  // cpu/chipset requests write
	.p2_ack        ( fastram_ready   )
);

// run the flash a 85MHz. This is only used at power-up to copy kickstart
// from flash to sdram
assign mspi_clk = clk_85m_shifted;   
flash flash (
    .clk       ( clk_85m     ),
    .resetn    ( rst_85m_n   ),
    .ready     ( flash_ready ),

    .address   ( flash_addr  ),
    .cs        ( flash_cs    ),
    .dout      ( flash_dout  ),
	.busy      ( flash_busy  ),

    .mspi_cs   ( mspi_cs     ),
    .mspi_di   ( mspi_di     ),
    .mspi_hold ( mspi_hold   ),
    .mspi_wp   ( mspi_wp     ),
    .mspi_do   ( mspi_do     )
);

/* -------------------- LCD video and audio -------------------- */

wire vreset, vpal, interlace;
video_analyzer video_analyzer (
    .clk       ( clk_28m   ),
    .hs        ( hs_n      ),
    .vs        ( vs_n      ),
    .pal       ( vpal      ),
    .short_frame ( ),
    .screen    ( 2'd1 ),
    .interlace ( interlace ),
    .vreset    ( vreset    )
);
   
assign lcd_dclk = clk_pixel;
assign lcd_hs = hs_n;
assign lcd_vs = vs_n;
assign lcd_bl = !nanomig_reset;   // enable display backlight once cpu is out of reset

reg [9:0] hcnt;   // max 1023
reg [9:0] vcnt;   // max 626

// generate the 800x480 pixel display enable signal 
assign lcd_de = (hcnt < 10'd800) && (vcnt < 10'd480);

always @(posedge clk_pixel) begin
   reg       last_vs_n, last_hs_n;

   last_hs_n <= lcd_hs;   

   // rising edge/end of hsync
   if(lcd_hs && !last_hs_n) begin
      hcnt <= 10'd980;

      last_vs_n <= lcd_vs;   
      if(lcd_vs && !last_vs_n) begin
         vcnt <= 10'd946 - { {2{osd_lcd_v_pos[7]}}, osd_lcd_v_pos };
      end else
        vcnt <= vcnt + 10'd1;    
   end else
      hcnt <= hcnt + 10'd1;    
end

/* ------------------- audio processing --------------- */

// MAX98357A
   
// EN is actually the /SD_MODE of the MAX98357A and driving it high selects
// left channel only. For stereo mixing there would have to be a "large" 
// resistor as a pullup which isn't there on the TN20k

assign pa_en = !nanomig_reset;   // simply enable amplifier with left channel

// latch audio, so it's stable during 48khz transfer
reg [14:0] scaled_audio_left;
reg [14:0] scaled_audio_right;

reg clk_audio;
reg [7:0] aclk_cnt;
always @(posedge clk_28m) begin
    if(aclk_cnt < 28375160 / (24000*32) / 2 - 1)
        aclk_cnt <= aclk_cnt + 8'd1;
    else begin
        aclk_cnt <= 8'd0;
        clk_audio <= ~clk_audio;

	    // Scale values and Assign scaled values to the HDMI registers
        case (osd_volume) 
            3'b100: begin // 100%
                scaled_audio_left  <= audio_left;
                scaled_audio_right <= audio_right;
            end
            3'b011: begin // 75%
                scaled_audio_left  <= ($signed(audio_left)  >>> 1) + ($signed(audio_left)  >>> 2);
                scaled_audio_right <= ($signed(audio_right) >>> 1) + ($signed(audio_right) >>> 2);
            end
            3'b010: begin // 50%
                scaled_audio_left  <= $signed(audio_left)  >>> 1;
                scaled_audio_right <= $signed(audio_right) >>> 1;
            end
            3'b001: begin // 25%
                scaled_audio_left  <= $signed(audio_left)  >>> 2;
                scaled_audio_right <= $signed(audio_right) >>> 2;
            end
            3'b000: begin // Mute
                scaled_audio_left  <= 15'd0;
                scaled_audio_right <= 15'd0;
            end
            default: begin
                scaled_audio_left  <= $signed(audio_left)  >>> 1;
                scaled_audio_right <= $signed(audio_right) >>> 1;
            end
        endcase
    end
end

// sign expand and add both channels
wire [15:0] audio_mix = { scaled_audio_left[14], scaled_audio_left} + { scaled_audio_right[14], scaled_audio_right };

// shift audio down to reduce amp output volume to a sane range
localparam AUDIO_SHIFT = 3;   
wire [15:0] audio_scaled = { { AUDIO_SHIFT+1{audio_mix[15]}}, audio_mix[14:AUDIO_SHIFT] };   

// count 32 bits, 16 left and 16 right channel. MAX samples
// on rising edge
reg [15:0] audio;
reg [4:0] audio_bit_cnt;
always @(posedge clk_audio) begin
   if(nanomig_reset) audio_bit_cnt <= 5'd0;
   else              audio_bit_cnt <= audio_bit_cnt + 5'd1;

   // latch data so it's stable during transmission
   if(audio_bit_cnt == 5'd31)
	 audio <= audio_scaled;
end

// generate i2s signals
assign hp_bck = !clk_audio;
assign hp_ws = nanomig_reset?1'b0:audio_bit_cnt[4];
assign hp_din = nanomig_reset?1'b0:audio[15-audio_bit_cnt[3:0]];

// ========================= Drive Sounds =========================
`ifdef ENABLE_DRIVE_SOUNDS	
drive_sounds drive_sounds_inst (
    .clk     (clk_28m),
	.enable  (osd_drive_sounds),
    //.fdd_led (leds[1]),
    .hdd_led (leds[2]),
    .buzzer  (buzzer)
);
`endif
   
endmodule

// To match emacs with gw_ide default
// Local Variables:
// tab-width: 4
// End:
`default_nettype wire
